rem generated by runnung for %i in (r\*.png) do echo node split.js rotate %i >>a.bat

node split.js rotate r\1t.png 
node split.js rotate r\2b.png 
node split.js rotate r\2t.png 
node split.js rotate r\7b.png 
node split.js rotate r\7t.png 
node split.js rotate r\7w.png 
node split.js rotate r\east.png 
node split.js rotate r\fall.png 
node split.js rotate r\ju.png 
node split.js rotate r\lan.png 
node split.js rotate r\mei.png 
node split.js rotate r\spring.png 
node split.js rotate r\summer.png 
node split.js rotate r\winter.png 
node split.js rotate r\zhu.png 
